### ISSUE TITLE
Why a4wide?

### ISSUE THREAD

**Issue by prowlett** [chirun-ncl/chirun#122]
Is there a good reason to use [a4wide](https://www.ctan.org/pkg/a4wide)? I had thought the principle was if you are using LaTeX that the PDF version would look exactly as you would expect from pdflatex and the HTML is an accessible version of this styled by chirun. I then thought the package `chirun.sty` was there to deal with some code that is there for the HTML version and how this code should be handled by pdflatex, like embedding and alt text. But now I find that `chirun.sty` is making a specific decision about how to lay out the PDF version. 

It's a particular bother today because of interaction with other LaTeX packages, like in order to get alt text and links on the web version of a two page document I'm going to print for class this week and to avoid it becoming a three page document, I've had to manage loading packages in a very specific order and I'm not really sure why the end user should have to think about this.

```
\documentclass[a4paper]{article}
\usepackage[hidelinks]{hyperref}
\usepackage{chirun}
\usepackage[margin=...]{geometry}
...
```

**Comment by georgestagg** [comment]
`a4wide` has been in the Chirun/makecourse LaTeX support .sty file for a long time, since near the beginning of development. I can't remember the original reasoning for it now.

You are right in that Chirun should probably not be making that decision for the user. When I have time to return to Chirun development I'll investigate if the package is required (my gut feeling is that it's not) and remove it if possible.

**Comment by georgestagg** [comment]
`a4wide` has now been removed from the packages loaded by the `chirun` package.
