### ISSUE TITLE
Rename "accessible" theme something like "big text, high contrast"

### ISSUE THREAD

**Issue by christianp** [chirun-ncl/chirun#20]
We should be aiming for universal design: the default theme should be accessible for as many people as possible.

What's now called the 'accessible' theme should maybe be renamed, to describe the ways in which it was modified from the default theme.

Ideally, the default theme would be sufficiently customisable and follow browser-reported preferences, so a separate theme isn't necessary.

**Comment by extigy** [comment]
I agree that the default theme should be accessible for as many people as possible but I think there is still a place for what is currently called the 'accessible' theme.

Even if the default theme can be heavily customised I'd still like to make something available with a simple structure and with things like big-text enabled by default, rather than hidden behind javascript based customisation toggles.

The theme was born out of necessity and the current name is an improvement over its original name (simply the surname of our primary user of that theme), but still not ideal. I'm wary of long names, perhaps something like 'clear' or 'simple' still reflects the nature of the theme?

**Comment by christianp** [comment]
I don't think 'clear' and 'simple' are better - they're even more abstract.

Could we make a list of things that the 'accessible' thing does differently, and see which ones really need a separate theme?

**Comment by georgestagg** [comment]
The old "accessible" theme has now been deleted. The default theme can now do the kinds of things it was originally used for via customisation.
