### ISSUE TITLE
Tikz figures should be handled in plasTeX

### ISSUE THREAD

**Issue by georgestagg** [chirun-ncl/chirun#22]
Tikz figures are supposed to be automatically compiled in an independent LaTeX run and converted to .svg to be included in the html output. This was always a bit shaky but the process seems to have broken completely at some point (recently?).

**Comment by prowlett** [comment]
I'm pleased to hear this is a goal, and a bug. I tried it and it didn't work (dumped the tikz code into the HTML file), and was mindful of the advice "not all packages are compatible ... Try removing one or more, simplifying your notes, until things start working", so assumed it was not available. Brilliant if it can be got working again!

**Comment by extigy** [comment]
Commit 2691c51719e902bbfafe63bc360f250775fb4629 takes some committed but as yet unreleased changes in the plasTeX source and implements them as part of makecourse. Specifically, the pdf2svg imager is added, and the tikz packages have been re-implemented use that imager.

Once a new version of plasTeX incorporating these changes has been
released, these parts of makecourse should be removed so that we simply rely on the tikz package and pdf2svg imager provided by plasTeX.

Hopefully this should get simple tikz plots mostly working again but things will probably remain shaky, so I have left the issue open (slightly renamed) for now.

**Comment by christianp** [comment]
Hah, I spent a few hours hacking in a pdf2svg imager at the weekend! Glad I gave up on it.

**Comment by christianp** [comment]
tikz figures are now generated in a separate LaTeX run and converted to SVG.
