### ISSUE TITLE
Changed image not picked up as input file change

### ISSUE THREAD

**Issue by prowlett** [chirun-ncl/chirun#68]
An unforeseen consequence of the switch to not re-running files that haven't changed*. 

I have a file like this

```
\documentclass{article}
\usepackage{graphicx}
\begin{document}
\includegraphics{image.png}
\end{document}
```

and I run `makecourse`. Then I change the image file (today I was doing some how-to screenshots for a piece of software that has updated its interface so I had the same filenames in the same places but just updated the pictures), and run `makecourse` again. 

As far as I am concerned, one of the the underpinning source files for this LaTeX file have changed, but `makecourse` does not recognise this and so skips the file. I note that the `.fls` file does contain `image.png` as an `INPUT` (several times actually; I don't understand .fls), so is `makecourse` correctly checking when this file was last updated? 

I could get it to re-run the file with the new image by making an arbitrary change to the file, such as an additional space somewhere in the file. I thought it was also re-running when I deleted the `.fls` file, but it seems to re-run but doesn't seem to copy across the new image file. I can investigate further but not right now, so I'm going to submit and look into it if you ask me to.

\* Note I still strongly support the change. It is making my use of coursebuilder a lot better, because I can make small changes and re-run without waiting minutes, making development of notes smoother.

**Comment by georgestagg** [comment]
`makecourse` should be able to detect when images used by a `.tex` file have changed and re-generate the output. This could be similar to #73 in that the problem is that the last-modified time of the replacement image file is earlier than the outputted HTML page. I'm not sure how that might happen, but perhaps renaming a file rather than making a copy doesn't trigger a modification? Can you remember in what way you updated your pictures?

As in #73, can you try running `touch image.png` before running `makecourse` to update the last-modified attribute of the image file and see if that triggers a rebuild?

As I understand it, files have both a "modified" and "changed" timestamp which report subtly different things, and some file systems also support a "created" timestamp. One option I could implement would be to take the latest of those timestamps and work with that.

**Comment by prowlett** [comment]
Interesting, thanks (and for the response to #73). I had forgotten about `touch`, good call. 

Yes, I think this is a problem with last modified times as you suggest. 

- Before 11:57:01 I had created two image files, `image.png` and `image2.png` and placed them in a folder alongside a `.tex` file containing the above code. 
- At 11:57:01 I ran `makecourse` (updated to f8c714a) and the output was as expected. 
- At 11:58:05 I deleted `image.png` and renamed `image2.png` as `image.png`. 
- At 11:58:20 I ran `makecourse` again. The output image had not changed. 
- At 11:59:25 I ran `touch image2.png`.
- At 11:59:28 I ran `makecourse` again. The image had changed.

**Comment by christianp** [comment]
For reference, GNU `make` has the same behaviour: I made files `a` and `b`, and set a make rule `c: a`, then ran `make`. I then changed the rule to `c: b`, and when I ran `make` again it said "'c' is up to date.
So don't fret too much about keeping track of which files were used to build what.

**Comment by prowlett** [comment]
So maybe this is a hard problem to solve and should just be documented as a quirk? (Applies also to #73.)

**Comment by christianp** [comment]
I think that's a good idea.

**Comment by georgestagg** [comment]
Since this seems to be a general issue also affecting build systems like Make, I have left things as they are and added a warning to the docs to mention the behaviour.
