### ISSUE TITLE
makecourse doesn't notice input file change

### ISSUE THREAD

**Issue by prowlett** [chirun-ncl/chirun#73]
Say I make two files at the same time, `test-file1.tex` like this:

```
\documentclass{article}
\begin{document}
Hello.
\end{document}
```

and `test-file2.tex` like this:

```
\documentclass{article}
\begin{document}
Goodbye.
\end{document}
```

In `config.yml` I include the following and run `makecourse`. For the avoidance of doubt: I do not mention `test-file2.tex` in `config.yml` at this stage. 

```
    - type: chapter
      title: Test page
      source: test-file1.tex
```

This generates `test-file1.aux`, `test-file1.fls` and `test-file1.log`. The result is a HTML page 'Test page' and a PDF file both saying "Hello". 

Later I change the entry in `config.yml` to this and run `makecourse` again. For the avoidance of doubt: I do not mention `test-file1.tex` in `config.yml` at this stage. 

```
    - type: chapter
      title: Test page
      source: test-file2.tex
```

This generates `test-file2.aux`, `test-file2.fls` and `test-file2.log`. The result is a HTML page 'Test page' and a PDF file - but the HTML page says "Hello" and the PDF file says "Goodbye". I was expecting both to say "Goodbye". 

If I edit `test-file2.tex`, say by adding a space somewhere where it won't make a difference, then run `makecourse` again, it build HTML and PDF versions both saying "Goodbye". 

The problem, as far as I can tell, is that `makecourse` is comparing the last build time for `test-file1.tex` (perhaps looking at `test-file1.fls`?) to the last edited time of `test-file2.tex` (which does not have an `.fls`), and not noticing that this is a totally different source file with a different name. Meanwhile, `test-file2.tex` is being used to generate a new PDF correctly.

The use case is that I often prepare pre- and post-class versions of slides/notes, with the former omitting certain spoilers/answers. I release the partial slides for the students to use during the class and save the full version for me to use during class and for release to students after the class.

**Comment by georgestagg** [comment]
When you edit `config.yml` to switch the source to `test-file2.tex`, `makecourse` sees that the the last modified time of the existing output HTML file is newer than the last modified time of the file `test-file2.tex`, so doesn't rebuild the HTML page. It does, however, re-run `pdflatex` because the `test-file2.fls` file doesn't exist. Unfortunately we can't rely on that for HTML output because PDF output might be turned off.

A quick workaround for now might be to run the command `touch test-file2.tex` in a terminal to update the last-modified time on the file, before running `makecourse`. That should be easier than modifying the file using spaces.

A proper fix will probably involve tweaking things so that the source filename of an item is stored somewhere and compared to the contents of `config.yml` when building.
