### ISSUE TITLE
Centering within list \item

### ISSUE THREAD

**Issue by prowlett** [chirun-ncl/chirun#84]
A minor thing. For Reasons I'm trying to centre something that is part of a list `\item`. LaTeX doesn't like `\begin{center}` inside a list. The solution appears to be 

```
\item \hfil thing
```

However, the HTML output does not centre. 

I can get the HTML output to centre using `\centering`, as in

```
\item {\centering thing}
```

but the PDF does not centre when I do this.

So altogether I have `\usepackage{makecourse}` and this:

```
\item {\ifplastex\centering\else\hfil\fi thing}
```

**Comment by christianp** [comment]
I think the correct way to implement `\hfil` in HTML is with flexbox, but it would need the CSS `:has` function in order to apply `display: flex` to the parent of the `\hfil`. 

I've put a commit in the branch `issue-84-hfil` that has a go at doing this. I'm not keen on trying to implement LaTeX spacing commands in HTML - the layout models are completely different so it feels like a fool's game.

It's a shame that `\centering` doesn't work within an `\item` - that looks like the semantic way of marking up what you want.

Can we close this issue as "won't fix"?

**Comment by prowlett** [comment]
You can do as you like. I can't remember the context for this, but no doubt I'll come across it again as we go through the year and I teach that bit. But it's a niche use case, and I can `\ifplastex` my way around it, so if it's a hassle it sounds like a 'won't fix'.
